

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
      POSTGRES_DB: postgres_cadastro_ifood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados

  app:
    image: postgres:14  # Substitua pela imagem do seu aplicativo Quarkus
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgres
      QUARKUS_DATASOURCE_USERNAME: cadastro
      QUARKUS_DATASOURCE_PASSWORD: cadastro
      QUARKUS_DATASOURCE_DATABASE: postgres_cadastro_ifood
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/postgres_cadastro_ifood  # URL para conectar ao banco
    ports:
      - "8080:8080"  # Porta do seu aplicativo
    depends_on:
      - db  # Garantir que o banco de dados esteja disponível antes de iniciar o aplicativo

volumes:
  postgres_data:  # Volume para persistir dados do PostgreSQL
